/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// allow-any-unicode-comment-file
// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts

import type { URI } from '../common/state.js';
import type { BaseParams } from '../common/commands.js';
import type { Message } from './state.js';

// ─── createChat ──────────────────────────────────────────────────────────────

/**
 * How a new chat uses its source chat and turn.
 */
export const enum ChatSourceKind {
	/** Copy source history through the referenced turn into the new chat. */
	Fork = 'fork',
	/** Supply source context without copying it into the new chat's visible history. */
	SideChat = 'sideChat',
}

/**
 * Identifies a source chat and completed turn for a new chat.
 *
 */
export interface ChatSource {
	/** How the source is used. */
	kind: ChatSourceKind;
	/** URI of the existing source chat. */
	chat: URI;
	/**
	 * Completed turn in the source chat. For a fork, content through this turn is
	 * copied. For a side chat, that content is supplied as context but is not
	 * copied into the new chat's visible `turns`.
	 */
	turnId: string;
}

/**
 * Creates a new chat within a session.
 *
 * @category Commands
 * @method createChat
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface CreateChatParams extends BaseParams {
	/** Session URI containing the new chat. */
	channel: URI;
	/** Chat URI (client-chosen, e.g. `ahp-chat:/<uuid>`). */
	chat: URI;
	/** Optional initial message for the new chat. */
	initialMessage?: Message;
	/**
	 * Optional source chat and completed turn.
	 *
	 * The source chat MUST belong to this session. Clients MUST only request
	 * `kind: "sideChat"` when the selected agent advertises
	 * `capabilities.multipleChats.sideChat`.
	 */
	source?: ChatSource;
	/**
	 * Initial working-directory subset for this chat. Every entry MUST be
	 * present in the owning session's `workingDirectories`; the server MUST
	 * reject any entry that is not. When absent, the chat inherits the full
	 * session set. Chats created from a source (`source`) inherit the source
	 * chat's `workingDirectories`; this field is ignored when `source` is set.
	 *
	 * A client MUST NOT supply this field unless the agent advertises
	 * {@link AgentCapabilities.multipleWorkingDirectories}.
	 */
	workingDirectories?: URI[];
	/**
	 * The chat's primary working directory — the distinguished root this chat is
	 * centered on. When set, it MUST be one of the chat's effective working
	 * directories ({@link workingDirectories}, or the session's set when that is
	 * omitted). A client SHOULD supply this when the agent advertises
	 * {@link MultipleWorkingDirectoriesCapability.requiresPrimary}; a host MAY
	 * reject creation that omits it, or fall back to the first of the chat's
	 * directories. Fixed at creation and reported (read-only) on
	 * {@link ChatState.primaryWorkingDirectory}. Ignored when `source` is set (the
	 * new chat inherits the source chat's primary).
	 */
	primaryWorkingDirectory?: URI;
}

// ─── disposeChat ─────────────────────────────────────────────────────────────

/**
 * Disposes a chat and cleans up server-side resources.
 *
 * @category Commands
 * @method disposeChat
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface DisposeChatParams extends BaseParams { }
