/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// allow-any-unicode-comment-file
// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts

import type { URI } from '../common/state.js';
import type { BaseParams } from '../common/commands.js';
import type { ChatSourceTurn, Message } from './state.js';

// ─── createChat ──────────────────────────────────────────────────────────────

/**
 * How a new chat uses its source chat and turn.
 */
export const enum ChatSourceKind {
	/** Copy source history through the referenced turn into the new chat. */
	Fork = 'fork',
	/** Supply source context without copying it into the new chat's visible history. */
	SideChat = 'sideChat',
}

/**
 * Copies source history through a completed turn into the new chat.
 */
export interface ForkChatSource {
	/** URI of the existing source chat. */
	chat: URI;
	/**
	 * Completed turn identifier in the source chat.
	 *
	 * Content through this turn is copied into the new chat's visible `turns`.
	 * This preserves the existing 0.7.x flat fork wire format (`chat` +
	 * `turnId`).
	 */
	turnId: string;
}

/**
 * Supplies source context to a new side chat without copying it into the side
 * chat's visible history.
 */
export interface SideChatSource {
	/** Discriminant */
	kind: ChatSourceKind.SideChat;
	/** URI of the existing source chat. */
	chat: URI;
	/**
	 * Source turn in the source chat.
	 *
	 * When this is `kind: "completed"`, the side chat is seeded from the source
	 * chat's retained history through that turn. When this is `kind: "active"`,
	 * the host snapshots the source chat's retained history plus the active turn's
	 * current user message and any partial assistant response already available
	 * when accepting `createChat`.
	 */
	turn: ChatSourceTurn;
}

/**
 * Identifies a source chat for a new chat.
 */
export type ChatSource =
	| ForkChatSource
	| SideChatSource;

/**
 * Creates a new chat within a session.
 *
 * @category Commands
 * @method createChat
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface CreateChatParams extends BaseParams {
	/** Session URI containing the new chat. */
	channel: URI;
	/** Chat URI (client-chosen, e.g. `ahp-chat:/<uuid>`). */
	chat: URI;
	/** Optional initial message for the new chat. */
	initialMessage?: Message;
	/**
	 * Optional source chat and source turn.
	 *
	 * The source chat MUST belong to this session. Clients MUST only request the
	 * flat fork shape (`chat` + `turnId`) when the selected agent advertises
	 * `capabilities.multipleChats.fork`, and
	 * `kind: "sideChat"` when the selected agent advertises
	 * `capabilities.multipleChats.sideChat`. Forks keep the legacy flat
	 * `chat` + `turnId` shape and therefore only target completed turns. Side
	 * chats use `source.turn.kind` to distinguish a completed source turn from
	 * the source chat's current active turn.
	 */
	source?: ChatSource;
	/**
	 * Initial working-directory subset for this chat. Every entry MUST be
	 * present in the owning session's `workingDirectories`; the server MUST
	 * reject any entry that is not. When absent, the chat inherits the full
	 * session set. Forked chats (those whose `source` uses the flat `chat` +
	 * `turnId` shape) inherit the source chat's `workingDirectories`; this field
	 * is ignored for forks.
	 *
	 * A client MUST NOT supply this field unless the agent advertises
	 * {@link AgentCapabilities.multipleWorkingDirectories}.
	 */
	workingDirectories?: URI[];
	/**
	 * The chat's primary working directory — the distinguished root this chat is
	 * centered on. When set, it MUST be one of the chat's effective working
	 * directories ({@link workingDirectories}, or the session's set when that is
	 * omitted). A client SHOULD supply this when the agent advertises
	 * {@link MultipleWorkingDirectoriesCapability.requiresPrimary}; a host MAY
	 * reject creation that omits it, or fall back to the first of the chat's
	 * directories. Fixed at creation and reported (read-only) on
	 * {@link ChatState.primaryWorkingDirectory}. Ignored for forks (a chat whose
	 * `source` uses the flat `chat` + `turnId` shape inherits the source chat's
	 * primary).
	 */
	primaryWorkingDirectory?: URI;
}

// ─── disposeChat ─────────────────────────────────────────────────────────────

/**
 * Disposes a chat and cleans up server-side resources.
 *
 * @category Commands
 * @method disposeChat
 * @direction Client → Server
 * @messageType Request
 * @version 1
 */
export interface DisposeChatParams extends BaseParams { }
